#############################################################################
# Makefile for building: dist/Debug/GNU-Linux-x86/ipanforlinux
# Generated by qmake (2.01a) (Qt 4.8.4) on: mar. nov. 5 21:27:32 2013
# Project:  ipangui.pro
# Template: app
# Command: /usr/lib/i386-linux-gnu/qt4/bin/qmake -o Makefile ipangui.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtScript -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -L./ -lQtScript -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/i386-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ipangui.cpp \
		IOauth.cpp \
		login.cpp \
		preferences.cpp \
		inotifythread.cpp \
		uploadthread.cpp \
		filetree.cpp \
		treedialog.cpp \
		filedownuplist.cpp moc_ipangui.cpp \
		moc_IOauth.cpp \
		moc_login.cpp \
		moc_preferences.cpp \
		moc_inotifythread.cpp \
		moc_uploadthread.cpp \
		moc_filetree.cpp \
		moc_treedialog.cpp \
		moc_filedownuplist.cpp
OBJECTS       = main.o \
		ipangui.o \
		IOauth.o \
		login.o \
		preferences.o \
		inotifythread.o \
		uploadthread.o \
		filetree.o \
		treedialog.o \
		filedownuplist.o \
		moc_ipangui.o \
		moc_IOauth.o \
		moc_login.o \
		moc_preferences.o \
		moc_inotifythread.o \
		moc_uploadthread.o \
		moc_filetree.o \
		moc_treedialog.o \
		moc_filedownuplist.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ipangui.pro
QMAKE_TARGET  = ipanforlinux
DESTDIR       = dist/Debug/GNU-Linux-x86/
TARGET        = dist/Debug/GNU-Linux-x86/ipanforlinux

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_preferences.h ui_login.h ui_treedialog.h ui_filelist.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) dist/Debug/GNU-Linux-x86/ || $(MKDIR) dist/Debug/GNU-Linux-x86/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ipangui.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtScript.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtNetwork.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile ipangui.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtScript.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtNetwork.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile ipangui.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ipanforlinux1.0.0 || $(MKDIR) .tmp/ipanforlinux1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ipanforlinux1.0.0/ && $(COPY_FILE) --parents ipangui.h IOauth.h login.h preferences.h public.h inotifythread.h uploadthread.h filetree.h treedialog.h filedownuplist.h .tmp/ipanforlinux1.0.0/ && $(COPY_FILE) --parents main.cpp ipangui.cpp IOauth.cpp login.cpp preferences.cpp inotifythread.cpp uploadthread.cpp filetree.cpp treedialog.cpp filedownuplist.cpp .tmp/ipanforlinux1.0.0/ && $(COPY_FILE) --parents ui/preferences.ui ui/login.ui ui/treedialog.ui ui/filelist.ui .tmp/ipanforlinux1.0.0/ && $(COPY_FILE) --parents cn_zh.ts .tmp/ipanforlinux1.0.0/ && (cd `dirname .tmp/ipanforlinux1.0.0` && $(TAR) ipanforlinux1.0.0.tar ipanforlinux1.0.0 && $(COMPRESS) ipanforlinux1.0.0.tar) && $(MOVE) `dirname .tmp/ipanforlinux1.0.0`/ipanforlinux1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ipanforlinux1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ipangui.cpp moc_IOauth.cpp moc_login.cpp moc_preferences.cpp moc_inotifythread.cpp moc_uploadthread.cpp moc_filetree.cpp moc_treedialog.cpp moc_filedownuplist.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ipangui.cpp moc_IOauth.cpp moc_login.cpp moc_preferences.cpp moc_inotifythread.cpp moc_uploadthread.cpp moc_filetree.cpp moc_treedialog.cpp moc_filedownuplist.cpp
moc_ipangui.cpp: public.h \
		login.h \
		ui_login.h \
		preferences.h \
		ui_preferences.h \
		IOauth.h \
		inotifythread.h \
		uploadthread.h \
		filedownuplist.h \
		ui_filelist.h \
		treedialog.h \
		ui_treedialog.h \
		filetree.h \
		ipangui.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) ipangui.h -o moc_ipangui.cpp

moc_IOauth.cpp: public.h \
		IOauth.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) IOauth.h -o moc_IOauth.cpp

moc_login.cpp: ui_login.h \
		public.h \
		login.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) login.h -o moc_login.cpp

moc_preferences.cpp: ui_preferences.h \
		public.h \
		preferences.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) preferences.h -o moc_preferences.cpp

moc_inotifythread.cpp: public.h \
		inotifythread.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) inotifythread.h -o moc_inotifythread.cpp

moc_uploadthread.cpp: public.h \
		IOauth.h \
		filedownuplist.h \
		ui_filelist.h \
		uploadthread.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) uploadthread.h -o moc_uploadthread.cpp

moc_filetree.cpp: IOauth.h \
		public.h \
		filetree.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) filetree.h -o moc_filetree.cpp

moc_treedialog.cpp: ui_treedialog.h \
		IOauth.h \
		public.h \
		filetree.h \
		treedialog.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) treedialog.h -o moc_treedialog.cpp

moc_filedownuplist.cpp: ui_filelist.h \
		filedownuplist.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) filedownuplist.h -o moc_filedownuplist.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_preferences.h ui_login.h ui_treedialog.h ui_filelist.h
compiler_uic_clean:
	-$(DEL_FILE) ui_preferences.h ui_login.h ui_treedialog.h ui_filelist.h
ui_preferences.h: ui/preferences.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic ui/preferences.ui -o ui_preferences.h

ui_login.h: ui/login.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic ui/login.ui -o ui_login.h

ui_treedialog.h: ui/treedialog.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic ui/treedialog.ui -o ui_treedialog.h

ui_filelist.h: ui/filelist.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic ui/filelist.ui -o ui_filelist.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ipangui.h \
		public.h \
		login.h \
		ui_login.h \
		preferences.h \
		ui_preferences.h \
		IOauth.h \
		inotifythread.h \
		uploadthread.h \
		filedownuplist.h \
		ui_filelist.h \
		treedialog.h \
		ui_treedialog.h \
		filetree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ipangui.o: ipangui.cpp ipangui.h \
		public.h \
		login.h \
		ui_login.h \
		preferences.h \
		ui_preferences.h \
		IOauth.h \
		inotifythread.h \
		uploadthread.h \
		filedownuplist.h \
		ui_filelist.h \
		treedialog.h \
		ui_treedialog.h \
		filetree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ipangui.o ipangui.cpp

IOauth.o: IOauth.cpp IOauth.h \
		public.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IOauth.o IOauth.cpp

login.o: login.cpp login.h \
		ui_login.h \
		public.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o login.cpp

preferences.o: preferences.cpp preferences.h \
		ui_preferences.h \
		public.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preferences.o preferences.cpp

inotifythread.o: inotifythread.cpp inotifythread.h \
		public.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inotifythread.o inotifythread.cpp

uploadthread.o: uploadthread.cpp uploadthread.h \
		public.h \
		IOauth.h \
		filedownuplist.h \
		ui_filelist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uploadthread.o uploadthread.cpp

filetree.o: filetree.cpp filetree.h \
		IOauth.h \
		public.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filetree.o filetree.cpp

treedialog.o: treedialog.cpp treedialog.h \
		ui_treedialog.h \
		IOauth.h \
		public.h \
		filetree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o treedialog.o treedialog.cpp

filedownuplist.o: filedownuplist.cpp filedownuplist.h \
		ui_filelist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filedownuplist.o filedownuplist.cpp

moc_ipangui.o: moc_ipangui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ipangui.o moc_ipangui.cpp

moc_IOauth.o: moc_IOauth.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_IOauth.o moc_IOauth.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_preferences.o: moc_preferences.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preferences.o moc_preferences.cpp

moc_inotifythread.o: moc_inotifythread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inotifythread.o moc_inotifythread.cpp

moc_uploadthread.o: moc_uploadthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uploadthread.o moc_uploadthread.cpp

moc_filetree.o: moc_filetree.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filetree.o moc_filetree.cpp

moc_treedialog.o: moc_treedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_treedialog.o moc_treedialog.cpp

moc_filedownuplist.o: moc_filedownuplist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filedownuplist.o moc_filedownuplist.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

